### PR TITLE
Implement support for Python3

### PR DESCRIPTION
**Pull request by evilaliv3**
The pull request, still not ready, is simply to keep track of work and patches needed in order to make cyclone compatible with python 3 as by https://github.com/fiorix/cyclone/issues/171 

\cc \@posita @dpnova @fiorix

### CODE REVIEW

**Comment by dpnova** [comment]
FYI @evilaliv3 looks like a conflict now after recent merges

**Comment by evilaliv3** [comment]
bam bam!

**Comment by dpnova** [comment]
:+1:

**Comment by auvipy** [comment]
LGTM!!

**Comment by dpnova** [comment]
yo @evilaliv3 how are you feeling about this one?

**Comment by evilaliv3** [comment]
i've not moved forward francly; i hope other users will be interested as i am in order to move this forward.

e.g. distributions like ubuntu 16.04 xenial (the current LTS) are now using python 3 as the default so this ticket is so important.

**Comment by dpnova** [comment]
Yeah, I'm willing to spend a bit of time getting it sorted. I'll have a bit of a play tomorrow.

**Comment by evilaliv3** [comment]
wonderful! for every need of retesting or review count on me.

**Pull request merged**
