### PR TITLE
Switch to python3

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` break `python2` compatibility

Thanks for @ygl-rg for his work :tada:

Checklist :
+ [x] Test passes on python3 (at least 3.5 / 3.6 / 3.7)
+ [x] Documentation is updated (to **warn** about `python3` support **dropping**)

@fiorix To keep this `PR` as minimalistic as I can, I think this is it (I'll add other feature later and / or maybe drop python3.5 support)

/cc @dpnova @posita

Regards,

### CODE REVIEW

**Comment by fiorix** [comment]
Woah, big PR :)

It actually looks alright. I'm surprised all tests pass, but wouldn't be surprised if it'd still break things silently given not everything is covered in these tests.

Have you looked at the travis output? It fails on python nightly - might be because of something else, but worth a glance.

**Comment by fiorix** [comment]
> What do you think of 2 lasts ?

I don't even know what black is. For editor, I only use vim, so.. :)

**Comment by waghanza** [comment]
@fiorix `black` is a `python` formatter => https://black.readthedocs.io

behind the idea of using it is to clean / homogenize the code base

PS : it's the smallest I've found (used massively by **mozilla**)

**Comment by waghanza** [comment]
@fiorix the last is about keeping code base uniform along `PR`

**Comment by fiorix** [comment]
ah, black is like gofmt for go, cool; I'm ok with using it and avoiding people debating style / pepX :)

**Comment by fiorix** [comment]
I guess it doesn't have to be in the same PR. This one is long enough already.

**Comment by waghanza** [comment]
of course, I think about listing stuff in origin issue instead of here

**Comment by ygl-rg** [comment]
glad to see "all checks have passed"

**Comment by tabnakk** [comment]
@@ -0,0 +1,14 @@
        1 +cask 'tmetricdesktop' do
        2 +  version '18.2.4'
        3 +  sha256 '995c4fae15b8f2c07034bec093b84710296cff0a780df874d2f6bbd06d34fa66'
        4 +
        5 +  url "https://static.tmetric.com/desktop/tmetric_desktop_#{version}.pkg"
        6 +  name 'TMetric'
        7 +  homepage 'https://tmetric.com/'
        8 +
        9 +  pkg "tmetric_desktop_#{version}.pkg"
       10 +
       11 +  uninstall signal:  ['TERM', 'com.company.TMetricDesktop'],
       12 +            pkgutil: 'com.company.TMetricDesktop',
       13 +            delete:  '/Applications/TMetricDesktop'
       14 +58640

**Comment by tabnakk** [comment]
@@ -0,0 +1,14 @@
        1 +cask 'tmetricdesktop' do
        2 +  version '18.2.4'
        3 +  sha256 '995c4fae15b8f2c07034bec093b84710296cff0a780df874d2f6bbd06d34fa66'
        4 +
        5 +  url "https://static.tmetric.com/desktop/tmetric_desktop_#{version}.pkg"
        6 +  name 'TMetric'
        7 +  homepage 'https://tmetric.com/'
        8 +
        9 +  pkg "tmetric_desktop_#{version}.pkg"
       10 +
       11 +  uninstall signal:  ['TERM', 'com.company.TMetricDesktop'],
       12 +            pkgutil: 'com.company.TMetricDesktop',
       13 +            delete:  '/Applications/TMetricDesktop'
       14 +#58640

**Comment by fiorix** [comment]
Hey could you please squash this in 1 commit before I merge it?

**Comment by waghanza** [comment]
Sure, I'll learn how to do it 😄

**Comment by waghanza** [comment]
I have squashed commits

**Comment by subyraman** [comment]
@fiorix do you have any thoughts about merging this? A number of us are excited for the possibility of this being Py3 compatible :)

**Comment by fiorix** [comment]
Hey all, this is fantastic work! Thank you so much.

**Comment by fiorix** [comment]
Made it release v1.3, and it should be pushed to pypi.

**Pull request merged**
