### PR TITLE
Fix test that was using unorderable datetime format.

### PR DESCRIPTION
**Pull request by dpnova**
Thanks!

Fixes comment by @fiorix noted here: https://github.com/fiorix/cyclone/pull/163

### CODE REVIEW

**Comment by dpnova** [comment]
Nudge @fiorix this one is currently breaking the build for everyone else! Thanks man

Side note: we have a fair few fixes we're currently maintain in our own fork - I'm happy to help out with maintaining if you like... just need contributor access to this repo.

**Comment by fiorix** [comment]
Bang!

**Comment by fiorix** [comment]
I guess we need new release on pypi now.

**Comment by dpnova** [comment]
I can coordinate with the other major dev at our end to see what should and shouldn't be included in a new release. cc: @lextoumbourou

**Comment by fiorix** [comment]
Sure, thanks!

**Pull request merged**
